{% set name = "stats_can" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf61e67d8fc43590dc241b3bf45c6d555cea1b4c12dd4d044c1d8247e53a9b85

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.8.13
  run:
    - python >={{ python_min }}
    - pandas
    - requests
    - tqdm
    - numpy
    - pydantic

test:
  requires:
    - python {{ python_min }}
  imports:
    - stats_can

about:
  home: https://github.com/ianepreston/stats_can
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Get Statistics Canada data into python (mostly pandas) '

  doc_url: https://stats-can.readthedocs.io/
  dev_url: https://github.com/ianepreston/stats_can

extra:
  recipe-maintainers:
    - ianepreston
