{% set name = "stats_can" %}
{% set version = "2.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab1f1fab765239533d32e51e1bfbb9d4673491dcea4ad0b7b2a0015a3fd56607

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.0
    - pip
    - poetry >=0.12
  run:
    - python >=3.0
    - pandas >=0.23
    - requests >=2.19
    - h5py >=2.8.0
    - pytables >=3.4.4
    - tqdm >=4.48.0

test:
  imports:
    - stats_can

about:
  home: https://github.com/ianepreston/stats_can
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Get Statistics Canada data into python (mostly pandas) '

  doc_url: https://stats-can.readthedocs.io/
  dev_url: https://github.com/ianepreston/stats_can

extra:
  recipe-maintainers:
    - ianepreston
