{% set name = "stats_can" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7593aa775334915b44b8b7aebc3ecf8a735669462bc48b6f32710df7bb3dbb8e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - pandas
    - requests
    - tqdm
    - pydantic
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - stats_can

about:
  home: https://github.com/ianepreston/stats_can
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Get Statistics Canada data into python (mostly pandas) '

  doc_url: https://stats-can.readthedocs.io/
  dev_url: https://github.com/ianepreston/stats_can

extra:
  recipe-maintainers:
    - ianepreston
